// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package handler

import (
	"github.com/google/wire"
	"go-grpc/services"
)

// Injectors from wire.go:

// CreateExampleHandler CreateExampleHandler
func CreateExampleHandler() *ExampleHandler {
	exampleService := services.CreateExampleService()
	exampleHandler := NewExampleHandler(exampleService)
	return exampleHandler
}

// wire.go:

var (
	ExampleHandlerSet = wire.NewSet(NewExampleHandler, services.CreateExampleService)
)
