// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateExampleService CreateExampleService
func CreateExampleService() *ExampleService {
	exampleService := NewExampleService()
	return exampleService
}

// wire.go:

var (
	ExampleServiceSet = wire.NewSet(NewExampleService)
)
